# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='customer.proto',
  package='trrp_3',
  syntax='proto2',
  serialized_options=b'\n\006trrp_3B\016CustomerProtos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x63ustomer.proto\x12\x06trrp_3\"\xec\x01\n\x08\x43ustomer\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x11\n\tfirstName\x18\x02 \x02(\t\x12\x10\n\x08lastName\x18\x03 \x02(\t\x12,\n\x05\x65mail\x18\x05 \x03(\x0b\x32\x1d.trrp_3.Customer.EmailAddress\x1aU\n\x0c\x45mailAddress\x12\r\n\x05\x65mail\x18\x01 \x02(\t\x12\x36\n\x04type\x18\x02 \x01(\x0e\x32\x1a.trrp_3.Customer.EmailType:\x0cPROFESSIONAL\"*\n\tEmailType\x12\x0b\n\x07PRIVATE\x10\x01\x12\x10\n\x0cPROFESSIONAL\x10\x02\"@\n\x0cOrganization\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\"\n\x08\x63ustomer\x18\x02 \x03(\x0b\x32\x10.trrp_3.CustomerB\x18\n\x06trrp_3B\x0e\x43ustomerProtos'
)



_CUSTOMER_EMAILTYPE = _descriptor.EnumDescriptor(
  name='EmailType',
  full_name='trrp_3.Customer.EmailType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRIVATE', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROFESSIONAL', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=221,
  serialized_end=263,
)
_sym_db.RegisterEnumDescriptor(_CUSTOMER_EMAILTYPE)


_CUSTOMER_EMAILADDRESS = _descriptor.Descriptor(
  name='EmailAddress',
  full_name='trrp_3.Customer.EmailAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='trrp_3.Customer.EmailAddress.email', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='trrp_3.Customer.EmailAddress.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=219,
)

_CUSTOMER = _descriptor.Descriptor(
  name='Customer',
  full_name='trrp_3.Customer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='trrp_3.Customer.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='firstName', full_name='trrp_3.Customer.firstName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastName', full_name='trrp_3.Customer.lastName', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='trrp_3.Customer.email', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CUSTOMER_EMAILADDRESS, ],
  enum_types=[
    _CUSTOMER_EMAILTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=263,
)


_ORGANIZATION = _descriptor.Descriptor(
  name='Organization',
  full_name='trrp_3.Organization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='trrp_3.Organization.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='customer', full_name='trrp_3.Organization.customer', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=329,
)

_CUSTOMER_EMAILADDRESS.fields_by_name['type'].enum_type = _CUSTOMER_EMAILTYPE
_CUSTOMER_EMAILADDRESS.containing_type = _CUSTOMER
_CUSTOMER.fields_by_name['email'].message_type = _CUSTOMER_EMAILADDRESS
_CUSTOMER_EMAILTYPE.containing_type = _CUSTOMER
_ORGANIZATION.fields_by_name['customer'].message_type = _CUSTOMER
DESCRIPTOR.message_types_by_name['Customer'] = _CUSTOMER
DESCRIPTOR.message_types_by_name['Organization'] = _ORGANIZATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Customer = _reflection.GeneratedProtocolMessageType('Customer', (_message.Message,), {

  'EmailAddress' : _reflection.GeneratedProtocolMessageType('EmailAddress', (_message.Message,), {
    'DESCRIPTOR' : _CUSTOMER_EMAILADDRESS,
    '__module__' : 'customer_pb2'
    # @@protoc_insertion_point(class_scope:trrp_3.Customer.EmailAddress)
    })
  ,
  'DESCRIPTOR' : _CUSTOMER,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:trrp_3.Customer)
  })
_sym_db.RegisterMessage(Customer)
_sym_db.RegisterMessage(Customer.EmailAddress)

Organization = _reflection.GeneratedProtocolMessageType('Organization', (_message.Message,), {
  'DESCRIPTOR' : _ORGANIZATION,
  '__module__' : 'customer_pb2'
  # @@protoc_insertion_point(class_scope:trrp_3.Organization)
  })
_sym_db.RegisterMessage(Organization)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
