// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package trrp_3;

public final class CustomerProtos {
  private CustomerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trrp_3.Customer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string firstName = 2;</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string firstName = 2;</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string lastName = 3;</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string lastName = 3;</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
     */
    java.util.List<trrp_3.CustomerProtos.Customer.EmailAddress> 
        getEmailsList();
    /**
     * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
     */
    trrp_3.CustomerProtos.Customer.EmailAddress getEmails(int index);
    /**
     * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
     */
    int getEmailsCount();
    /**
     * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
     */
    java.util.List<? extends trrp_3.CustomerProtos.Customer.EmailAddressOrBuilder> 
        getEmailsOrBuilderList();
    /**
     * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
     */
    trrp_3.CustomerProtos.Customer.EmailAddressOrBuilder getEmailsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code trrp_3.Customer}
   */
  public static final class Customer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trrp_3.Customer)
      CustomerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Customer.newBuilder() to construct.
    private Customer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customer() {
      firstName_ = "";
      lastName_ = "";
      emails_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Customer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Customer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              firstName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              lastName_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                emails_ = new java.util.ArrayList<trrp_3.CustomerProtos.Customer.EmailAddress>();
                mutable_bitField0_ |= 0x00000001;
              }
              emails_.add(
                  input.readMessage(trrp_3.CustomerProtos.Customer.EmailAddress.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          emails_ = java.util.Collections.unmodifiableList(emails_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return trrp_3.CustomerProtos.internal_static_trrp_3_Customer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trrp_3.CustomerProtos.internal_static_trrp_3_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trrp_3.CustomerProtos.Customer.class, trrp_3.CustomerProtos.Customer.Builder.class);
    }

    /**
     * Protobuf enum {@code trrp_3.Customer.EmailType}
     */
    public enum EmailType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PROFESSIONAL = 0;</code>
       */
      PROFESSIONAL(0),
      /**
       * <code>PRIVATE = 1;</code>
       */
      PRIVATE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PROFESSIONAL = 0;</code>
       */
      public static final int PROFESSIONAL_VALUE = 0;
      /**
       * <code>PRIVATE = 1;</code>
       */
      public static final int PRIVATE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EmailType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static EmailType forNumber(int value) {
        switch (value) {
          case 0: return PROFESSIONAL;
          case 1: return PRIVATE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EmailType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EmailType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EmailType>() {
              public EmailType findValueByNumber(int number) {
                return EmailType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return trrp_3.CustomerProtos.Customer.getDescriptor().getEnumTypes().get(0);
      }

      private static final EmailType[] VALUES = values();

      public static EmailType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EmailType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:trrp_3.Customer.EmailType)
    }

    public interface EmailAddressOrBuilder extends
        // @@protoc_insertion_point(interface_extends:trrp_3.Customer.EmailAddress)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string email = 1;</code>
       * @return The email.
       */
      java.lang.String getEmail();
      /**
       * <code>string email = 1;</code>
       * @return The bytes for email.
       */
      com.google.protobuf.ByteString
          getEmailBytes();

      /**
       * <code>.trrp_3.Customer.EmailType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      int getTypeValue();
      /**
       * <code>.trrp_3.Customer.EmailType type = 2;</code>
       * @return The type.
       */
      trrp_3.CustomerProtos.Customer.EmailType getType();
    }
    /**
     * Protobuf type {@code trrp_3.Customer.EmailAddress}
     */
    public static final class EmailAddress extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:trrp_3.Customer.EmailAddress)
        EmailAddressOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use EmailAddress.newBuilder() to construct.
      private EmailAddress(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private EmailAddress() {
        email_ = "";
        type_ = 0;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new EmailAddress();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private EmailAddress(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                email_ = s;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();

                type_ = rawValue;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return trrp_3.CustomerProtos.internal_static_trrp_3_Customer_EmailAddress_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return trrp_3.CustomerProtos.internal_static_trrp_3_Customer_EmailAddress_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                trrp_3.CustomerProtos.Customer.EmailAddress.class, trrp_3.CustomerProtos.Customer.EmailAddress.Builder.class);
      }

      public static final int EMAIL_FIELD_NUMBER = 1;
      private volatile java.lang.Object email_;
      /**
       * <code>string email = 1;</code>
       * @return The email.
       */
      @java.lang.Override
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        }
      }
      /**
       * <code>string email = 1;</code>
       * @return The bytes for email.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 2;
      private int type_;
      /**
       * <code>.trrp_3.Customer.EmailType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.trrp_3.Customer.EmailType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override public trrp_3.CustomerProtos.Customer.EmailType getType() {
        @SuppressWarnings("deprecation")
        trrp_3.CustomerProtos.Customer.EmailType result = trrp_3.CustomerProtos.Customer.EmailType.valueOf(type_);
        return result == null ? trrp_3.CustomerProtos.Customer.EmailType.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getEmailBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, email_);
        }
        if (type_ != trrp_3.CustomerProtos.Customer.EmailType.PROFESSIONAL.getNumber()) {
          output.writeEnum(2, type_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getEmailBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, email_);
        }
        if (type_ != trrp_3.CustomerProtos.Customer.EmailType.PROFESSIONAL.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, type_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof trrp_3.CustomerProtos.Customer.EmailAddress)) {
          return super.equals(obj);
        }
        trrp_3.CustomerProtos.Customer.EmailAddress other = (trrp_3.CustomerProtos.Customer.EmailAddress) obj;

        if (!getEmail()
            .equals(other.getEmail())) return false;
        if (type_ != other.type_) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static trrp_3.CustomerProtos.Customer.EmailAddress parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static trrp_3.CustomerProtos.Customer.EmailAddress parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static trrp_3.CustomerProtos.Customer.EmailAddress parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static trrp_3.CustomerProtos.Customer.EmailAddress parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static trrp_3.CustomerProtos.Customer.EmailAddress parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static trrp_3.CustomerProtos.Customer.EmailAddress parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static trrp_3.CustomerProtos.Customer.EmailAddress parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static trrp_3.CustomerProtos.Customer.EmailAddress parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static trrp_3.CustomerProtos.Customer.EmailAddress parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static trrp_3.CustomerProtos.Customer.EmailAddress parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static trrp_3.CustomerProtos.Customer.EmailAddress parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static trrp_3.CustomerProtos.Customer.EmailAddress parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(trrp_3.CustomerProtos.Customer.EmailAddress prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code trrp_3.Customer.EmailAddress}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:trrp_3.Customer.EmailAddress)
          trrp_3.CustomerProtos.Customer.EmailAddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return trrp_3.CustomerProtos.internal_static_trrp_3_Customer_EmailAddress_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return trrp_3.CustomerProtos.internal_static_trrp_3_Customer_EmailAddress_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  trrp_3.CustomerProtos.Customer.EmailAddress.class, trrp_3.CustomerProtos.Customer.EmailAddress.Builder.class);
        }

        // Construct using trrp_3.CustomerProtos.Customer.EmailAddress.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          email_ = "";

          type_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return trrp_3.CustomerProtos.internal_static_trrp_3_Customer_EmailAddress_descriptor;
        }

        @java.lang.Override
        public trrp_3.CustomerProtos.Customer.EmailAddress getDefaultInstanceForType() {
          return trrp_3.CustomerProtos.Customer.EmailAddress.getDefaultInstance();
        }

        @java.lang.Override
        public trrp_3.CustomerProtos.Customer.EmailAddress build() {
          trrp_3.CustomerProtos.Customer.EmailAddress result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public trrp_3.CustomerProtos.Customer.EmailAddress buildPartial() {
          trrp_3.CustomerProtos.Customer.EmailAddress result = new trrp_3.CustomerProtos.Customer.EmailAddress(this);
          result.email_ = email_;
          result.type_ = type_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof trrp_3.CustomerProtos.Customer.EmailAddress) {
            return mergeFrom((trrp_3.CustomerProtos.Customer.EmailAddress)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(trrp_3.CustomerProtos.Customer.EmailAddress other) {
          if (other == trrp_3.CustomerProtos.Customer.EmailAddress.getDefaultInstance()) return this;
          if (!other.getEmail().isEmpty()) {
            email_ = other.email_;
            onChanged();
          }
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          trrp_3.CustomerProtos.Customer.EmailAddress parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (trrp_3.CustomerProtos.Customer.EmailAddress) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object email_ = "";
        /**
         * <code>string email = 1;</code>
         * @return The email.
         */
        public java.lang.String getEmail() {
          java.lang.Object ref = email_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            email_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string email = 1;</code>
         * @return The bytes for email.
         */
        public com.google.protobuf.ByteString
            getEmailBytes() {
          java.lang.Object ref = email_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            email_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string email = 1;</code>
         * @param value The email to set.
         * @return This builder for chaining.
         */
        public Builder setEmail(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          email_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string email = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearEmail() {
          
          email_ = getDefaultInstance().getEmail();
          onChanged();
          return this;
        }
        /**
         * <code>string email = 1;</code>
         * @param value The bytes for email to set.
         * @return This builder for chaining.
         */
        public Builder setEmailBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          email_ = value;
          onChanged();
          return this;
        }

        private int type_ = 0;
        /**
         * <code>.trrp_3.Customer.EmailType type = 2;</code>
         * @return The enum numeric value on the wire for type.
         */
        @java.lang.Override public int getTypeValue() {
          return type_;
        }
        /**
         * <code>.trrp_3.Customer.EmailType type = 2;</code>
         * @param value The enum numeric value on the wire for type to set.
         * @return This builder for chaining.
         */
        public Builder setTypeValue(int value) {
          
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.trrp_3.Customer.EmailType type = 2;</code>
         * @return The type.
         */
        @java.lang.Override
        public trrp_3.CustomerProtos.Customer.EmailType getType() {
          @SuppressWarnings("deprecation")
          trrp_3.CustomerProtos.Customer.EmailType result = trrp_3.CustomerProtos.Customer.EmailType.valueOf(type_);
          return result == null ? trrp_3.CustomerProtos.Customer.EmailType.UNRECOGNIZED : result;
        }
        /**
         * <code>.trrp_3.Customer.EmailType type = 2;</code>
         * @param value The type to set.
         * @return This builder for chaining.
         */
        public Builder setType(trrp_3.CustomerProtos.Customer.EmailType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.trrp_3.Customer.EmailType type = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearType() {
          
          type_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:trrp_3.Customer.EmailAddress)
      }

      // @@protoc_insertion_point(class_scope:trrp_3.Customer.EmailAddress)
      private static final trrp_3.CustomerProtos.Customer.EmailAddress DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new trrp_3.CustomerProtos.Customer.EmailAddress();
      }

      public static trrp_3.CustomerProtos.Customer.EmailAddress getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<EmailAddress>
          PARSER = new com.google.protobuf.AbstractParser<EmailAddress>() {
        @java.lang.Override
        public EmailAddress parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new EmailAddress(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<EmailAddress> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<EmailAddress> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public trrp_3.CustomerProtos.Customer.EmailAddress getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int FIRSTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object firstName_;
    /**
     * <code>string firstName = 2;</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string firstName = 2;</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastName_;
    /**
     * <code>string lastName = 3;</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string lastName = 3;</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAILS_FIELD_NUMBER = 4;
    private java.util.List<trrp_3.CustomerProtos.Customer.EmailAddress> emails_;
    /**
     * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
     */
    @java.lang.Override
    public java.util.List<trrp_3.CustomerProtos.Customer.EmailAddress> getEmailsList() {
      return emails_;
    }
    /**
     * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends trrp_3.CustomerProtos.Customer.EmailAddressOrBuilder> 
        getEmailsOrBuilderList() {
      return emails_;
    }
    /**
     * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
     */
    @java.lang.Override
    public int getEmailsCount() {
      return emails_.size();
    }
    /**
     * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
     */
    @java.lang.Override
    public trrp_3.CustomerProtos.Customer.EmailAddress getEmails(int index) {
      return emails_.get(index);
    }
    /**
     * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
     */
    @java.lang.Override
    public trrp_3.CustomerProtos.Customer.EmailAddressOrBuilder getEmailsOrBuilder(
        int index) {
      return emails_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
      }
      for (int i = 0; i < emails_.size(); i++) {
        output.writeMessage(4, emails_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getFirstNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
      }
      if (!getLastNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
      }
      for (int i = 0; i < emails_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, emails_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof trrp_3.CustomerProtos.Customer)) {
        return super.equals(obj);
      }
      trrp_3.CustomerProtos.Customer other = (trrp_3.CustomerProtos.Customer) obj;

      if (getId()
          != other.getId()) return false;
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getEmailsList()
          .equals(other.getEmailsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      if (getEmailsCount() > 0) {
        hash = (37 * hash) + EMAILS_FIELD_NUMBER;
        hash = (53 * hash) + getEmailsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static trrp_3.CustomerProtos.Customer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trrp_3.CustomerProtos.Customer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trrp_3.CustomerProtos.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trrp_3.CustomerProtos.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trrp_3.CustomerProtos.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trrp_3.CustomerProtos.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trrp_3.CustomerProtos.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trrp_3.CustomerProtos.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static trrp_3.CustomerProtos.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static trrp_3.CustomerProtos.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static trrp_3.CustomerProtos.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trrp_3.CustomerProtos.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(trrp_3.CustomerProtos.Customer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trrp_3.Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trrp_3.Customer)
        trrp_3.CustomerProtos.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return trrp_3.CustomerProtos.internal_static_trrp_3_Customer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return trrp_3.CustomerProtos.internal_static_trrp_3_Customer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                trrp_3.CustomerProtos.Customer.class, trrp_3.CustomerProtos.Customer.Builder.class);
      }

      // Construct using trrp_3.CustomerProtos.Customer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEmailsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        firstName_ = "";

        lastName_ = "";

        if (emailsBuilder_ == null) {
          emails_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          emailsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return trrp_3.CustomerProtos.internal_static_trrp_3_Customer_descriptor;
      }

      @java.lang.Override
      public trrp_3.CustomerProtos.Customer getDefaultInstanceForType() {
        return trrp_3.CustomerProtos.Customer.getDefaultInstance();
      }

      @java.lang.Override
      public trrp_3.CustomerProtos.Customer build() {
        trrp_3.CustomerProtos.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public trrp_3.CustomerProtos.Customer buildPartial() {
        trrp_3.CustomerProtos.Customer result = new trrp_3.CustomerProtos.Customer(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.firstName_ = firstName_;
        result.lastName_ = lastName_;
        if (emailsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            emails_ = java.util.Collections.unmodifiableList(emails_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.emails_ = emails_;
        } else {
          result.emails_ = emailsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof trrp_3.CustomerProtos.Customer) {
          return mergeFrom((trrp_3.CustomerProtos.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(trrp_3.CustomerProtos.Customer other) {
        if (other == trrp_3.CustomerProtos.Customer.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          onChanged();
        }
        if (emailsBuilder_ == null) {
          if (!other.emails_.isEmpty()) {
            if (emails_.isEmpty()) {
              emails_ = other.emails_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEmailsIsMutable();
              emails_.addAll(other.emails_);
            }
            onChanged();
          }
        } else {
          if (!other.emails_.isEmpty()) {
            if (emailsBuilder_.isEmpty()) {
              emailsBuilder_.dispose();
              emailsBuilder_ = null;
              emails_ = other.emails_;
              bitField0_ = (bitField0_ & ~0x00000001);
              emailsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEmailsFieldBuilder() : null;
            } else {
              emailsBuilder_.addAllMessages(other.emails_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        trrp_3.CustomerProtos.Customer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (trrp_3.CustomerProtos.Customer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object firstName_ = "";
      /**
       * <code>string firstName = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string firstName = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string firstName = 2;</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        firstName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        
        firstName_ = getDefaultInstance().getFirstName();
        onChanged();
        return this;
      }
      /**
       * <code>string firstName = 2;</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        firstName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string lastName = 3;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string lastName = 3;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string lastName = 3;</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lastName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        
        lastName_ = getDefaultInstance().getLastName();
        onChanged();
        return this;
      }
      /**
       * <code>string lastName = 3;</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lastName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<trrp_3.CustomerProtos.Customer.EmailAddress> emails_ =
        java.util.Collections.emptyList();
      private void ensureEmailsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          emails_ = new java.util.ArrayList<trrp_3.CustomerProtos.Customer.EmailAddress>(emails_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          trrp_3.CustomerProtos.Customer.EmailAddress, trrp_3.CustomerProtos.Customer.EmailAddress.Builder, trrp_3.CustomerProtos.Customer.EmailAddressOrBuilder> emailsBuilder_;

      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public java.util.List<trrp_3.CustomerProtos.Customer.EmailAddress> getEmailsList() {
        if (emailsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(emails_);
        } else {
          return emailsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public int getEmailsCount() {
        if (emailsBuilder_ == null) {
          return emails_.size();
        } else {
          return emailsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public trrp_3.CustomerProtos.Customer.EmailAddress getEmails(int index) {
        if (emailsBuilder_ == null) {
          return emails_.get(index);
        } else {
          return emailsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public Builder setEmails(
          int index, trrp_3.CustomerProtos.Customer.EmailAddress value) {
        if (emailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmailsIsMutable();
          emails_.set(index, value);
          onChanged();
        } else {
          emailsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public Builder setEmails(
          int index, trrp_3.CustomerProtos.Customer.EmailAddress.Builder builderForValue) {
        if (emailsBuilder_ == null) {
          ensureEmailsIsMutable();
          emails_.set(index, builderForValue.build());
          onChanged();
        } else {
          emailsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public Builder addEmails(trrp_3.CustomerProtos.Customer.EmailAddress value) {
        if (emailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmailsIsMutable();
          emails_.add(value);
          onChanged();
        } else {
          emailsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public Builder addEmails(
          int index, trrp_3.CustomerProtos.Customer.EmailAddress value) {
        if (emailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEmailsIsMutable();
          emails_.add(index, value);
          onChanged();
        } else {
          emailsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public Builder addEmails(
          trrp_3.CustomerProtos.Customer.EmailAddress.Builder builderForValue) {
        if (emailsBuilder_ == null) {
          ensureEmailsIsMutable();
          emails_.add(builderForValue.build());
          onChanged();
        } else {
          emailsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public Builder addEmails(
          int index, trrp_3.CustomerProtos.Customer.EmailAddress.Builder builderForValue) {
        if (emailsBuilder_ == null) {
          ensureEmailsIsMutable();
          emails_.add(index, builderForValue.build());
          onChanged();
        } else {
          emailsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public Builder addAllEmails(
          java.lang.Iterable<? extends trrp_3.CustomerProtos.Customer.EmailAddress> values) {
        if (emailsBuilder_ == null) {
          ensureEmailsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, emails_);
          onChanged();
        } else {
          emailsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public Builder clearEmails() {
        if (emailsBuilder_ == null) {
          emails_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          emailsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public Builder removeEmails(int index) {
        if (emailsBuilder_ == null) {
          ensureEmailsIsMutable();
          emails_.remove(index);
          onChanged();
        } else {
          emailsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public trrp_3.CustomerProtos.Customer.EmailAddress.Builder getEmailsBuilder(
          int index) {
        return getEmailsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public trrp_3.CustomerProtos.Customer.EmailAddressOrBuilder getEmailsOrBuilder(
          int index) {
        if (emailsBuilder_ == null) {
          return emails_.get(index);  } else {
          return emailsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public java.util.List<? extends trrp_3.CustomerProtos.Customer.EmailAddressOrBuilder> 
           getEmailsOrBuilderList() {
        if (emailsBuilder_ != null) {
          return emailsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(emails_);
        }
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public trrp_3.CustomerProtos.Customer.EmailAddress.Builder addEmailsBuilder() {
        return getEmailsFieldBuilder().addBuilder(
            trrp_3.CustomerProtos.Customer.EmailAddress.getDefaultInstance());
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public trrp_3.CustomerProtos.Customer.EmailAddress.Builder addEmailsBuilder(
          int index) {
        return getEmailsFieldBuilder().addBuilder(
            index, trrp_3.CustomerProtos.Customer.EmailAddress.getDefaultInstance());
      }
      /**
       * <code>repeated .trrp_3.Customer.EmailAddress emails = 4;</code>
       */
      public java.util.List<trrp_3.CustomerProtos.Customer.EmailAddress.Builder> 
           getEmailsBuilderList() {
        return getEmailsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          trrp_3.CustomerProtos.Customer.EmailAddress, trrp_3.CustomerProtos.Customer.EmailAddress.Builder, trrp_3.CustomerProtos.Customer.EmailAddressOrBuilder> 
          getEmailsFieldBuilder() {
        if (emailsBuilder_ == null) {
          emailsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              trrp_3.CustomerProtos.Customer.EmailAddress, trrp_3.CustomerProtos.Customer.EmailAddress.Builder, trrp_3.CustomerProtos.Customer.EmailAddressOrBuilder>(
                  emails_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          emails_ = null;
        }
        return emailsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trrp_3.Customer)
    }

    // @@protoc_insertion_point(class_scope:trrp_3.Customer)
    private static final trrp_3.CustomerProtos.Customer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new trrp_3.CustomerProtos.Customer();
    }

    public static trrp_3.CustomerProtos.Customer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customer>
        PARSER = new com.google.protobuf.AbstractParser<Customer>() {
      @java.lang.Override
      public Customer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Customer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Customer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public trrp_3.CustomerProtos.Customer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListCustomersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:trrp_3.ListCustomers)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .trrp_3.Customer items = 1;</code>
     */
    java.util.List<trrp_3.CustomerProtos.Customer> 
        getItemsList();
    /**
     * <code>repeated .trrp_3.Customer items = 1;</code>
     */
    trrp_3.CustomerProtos.Customer getItems(int index);
    /**
     * <code>repeated .trrp_3.Customer items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .trrp_3.Customer items = 1;</code>
     */
    java.util.List<? extends trrp_3.CustomerProtos.CustomerOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .trrp_3.Customer items = 1;</code>
     */
    trrp_3.CustomerProtos.CustomerOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code trrp_3.ListCustomers}
   */
  public static final class ListCustomers extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:trrp_3.ListCustomers)
      ListCustomersOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ListCustomers.newBuilder() to construct.
    private ListCustomers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ListCustomers() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ListCustomers();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ListCustomers(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                items_ = new java.util.ArrayList<trrp_3.CustomerProtos.Customer>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(trrp_3.CustomerProtos.Customer.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return trrp_3.CustomerProtos.internal_static_trrp_3_ListCustomers_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return trrp_3.CustomerProtos.internal_static_trrp_3_ListCustomers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              trrp_3.CustomerProtos.ListCustomers.class, trrp_3.CustomerProtos.ListCustomers.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<trrp_3.CustomerProtos.Customer> items_;
    /**
     * <code>repeated .trrp_3.Customer items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<trrp_3.CustomerProtos.Customer> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .trrp_3.Customer items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends trrp_3.CustomerProtos.CustomerOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .trrp_3.Customer items = 1;</code>
     */
    @java.lang.Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .trrp_3.Customer items = 1;</code>
     */
    @java.lang.Override
    public trrp_3.CustomerProtos.Customer getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .trrp_3.Customer items = 1;</code>
     */
    @java.lang.Override
    public trrp_3.CustomerProtos.CustomerOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof trrp_3.CustomerProtos.ListCustomers)) {
        return super.equals(obj);
      }
      trrp_3.CustomerProtos.ListCustomers other = (trrp_3.CustomerProtos.ListCustomers) obj;

      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static trrp_3.CustomerProtos.ListCustomers parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trrp_3.CustomerProtos.ListCustomers parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trrp_3.CustomerProtos.ListCustomers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trrp_3.CustomerProtos.ListCustomers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trrp_3.CustomerProtos.ListCustomers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static trrp_3.CustomerProtos.ListCustomers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static trrp_3.CustomerProtos.ListCustomers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trrp_3.CustomerProtos.ListCustomers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static trrp_3.CustomerProtos.ListCustomers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static trrp_3.CustomerProtos.ListCustomers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static trrp_3.CustomerProtos.ListCustomers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static trrp_3.CustomerProtos.ListCustomers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(trrp_3.CustomerProtos.ListCustomers prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code trrp_3.ListCustomers}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:trrp_3.ListCustomers)
        trrp_3.CustomerProtos.ListCustomersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return trrp_3.CustomerProtos.internal_static_trrp_3_ListCustomers_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return trrp_3.CustomerProtos.internal_static_trrp_3_ListCustomers_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                trrp_3.CustomerProtos.ListCustomers.class, trrp_3.CustomerProtos.ListCustomers.Builder.class);
      }

      // Construct using trrp_3.CustomerProtos.ListCustomers.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return trrp_3.CustomerProtos.internal_static_trrp_3_ListCustomers_descriptor;
      }

      @java.lang.Override
      public trrp_3.CustomerProtos.ListCustomers getDefaultInstanceForType() {
        return trrp_3.CustomerProtos.ListCustomers.getDefaultInstance();
      }

      @java.lang.Override
      public trrp_3.CustomerProtos.ListCustomers build() {
        trrp_3.CustomerProtos.ListCustomers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public trrp_3.CustomerProtos.ListCustomers buildPartial() {
        trrp_3.CustomerProtos.ListCustomers result = new trrp_3.CustomerProtos.ListCustomers(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof trrp_3.CustomerProtos.ListCustomers) {
          return mergeFrom((trrp_3.CustomerProtos.ListCustomers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(trrp_3.CustomerProtos.ListCustomers other) {
        if (other == trrp_3.CustomerProtos.ListCustomers.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        trrp_3.CustomerProtos.ListCustomers parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (trrp_3.CustomerProtos.ListCustomers) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<trrp_3.CustomerProtos.Customer> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<trrp_3.CustomerProtos.Customer>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          trrp_3.CustomerProtos.Customer, trrp_3.CustomerProtos.Customer.Builder, trrp_3.CustomerProtos.CustomerOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public java.util.List<trrp_3.CustomerProtos.Customer> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public trrp_3.CustomerProtos.Customer getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public Builder setItems(
          int index, trrp_3.CustomerProtos.Customer value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public Builder setItems(
          int index, trrp_3.CustomerProtos.Customer.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public Builder addItems(trrp_3.CustomerProtos.Customer value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public Builder addItems(
          int index, trrp_3.CustomerProtos.Customer value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public Builder addItems(
          trrp_3.CustomerProtos.Customer.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public Builder addItems(
          int index, trrp_3.CustomerProtos.Customer.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends trrp_3.CustomerProtos.Customer> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public trrp_3.CustomerProtos.Customer.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public trrp_3.CustomerProtos.CustomerOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public java.util.List<? extends trrp_3.CustomerProtos.CustomerOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public trrp_3.CustomerProtos.Customer.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            trrp_3.CustomerProtos.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public trrp_3.CustomerProtos.Customer.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, trrp_3.CustomerProtos.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .trrp_3.Customer items = 1;</code>
       */
      public java.util.List<trrp_3.CustomerProtos.Customer.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          trrp_3.CustomerProtos.Customer, trrp_3.CustomerProtos.Customer.Builder, trrp_3.CustomerProtos.CustomerOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              trrp_3.CustomerProtos.Customer, trrp_3.CustomerProtos.Customer.Builder, trrp_3.CustomerProtos.CustomerOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:trrp_3.ListCustomers)
    }

    // @@protoc_insertion_point(class_scope:trrp_3.ListCustomers)
    private static final trrp_3.CustomerProtos.ListCustomers DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new trrp_3.CustomerProtos.ListCustomers();
    }

    public static trrp_3.CustomerProtos.ListCustomers getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListCustomers>
        PARSER = new com.google.protobuf.AbstractParser<ListCustomers>() {
      @java.lang.Override
      public ListCustomers parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListCustomers(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ListCustomers> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListCustomers> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public trrp_3.CustomerProtos.ListCustomers getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trrp_3_Customer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trrp_3_Customer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trrp_3_Customer_EmailAddress_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trrp_3_Customer_EmailAddress_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trrp_3_ListCustomers_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trrp_3_ListCustomers_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016customer.proto\022\006trrp_3\"\337\001\n\010Customer\022\n\n" +
      "\002id\030\001 \001(\005\022\021\n\tfirstName\030\002 \001(\t\022\020\n\010lastName" +
      "\030\003 \001(\t\022-\n\006emails\030\004 \003(\0132\035.trrp_3.Customer" +
      ".EmailAddress\032G\n\014EmailAddress\022\r\n\005email\030\001" +
      " \001(\t\022(\n\004type\030\002 \001(\0162\032.trrp_3.Customer.Ema" +
      "ilType\"*\n\tEmailType\022\020\n\014PROFESSIONAL\020\000\022\013\n" +
      "\007PRIVATE\020\001\"0\n\rListCustomers\022\037\n\005items\030\001 \003" +
      "(\0132\020.trrp_3.CustomerB\030\n\006trrp_3B\016Customer" +
      "Protosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_trrp_3_Customer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trrp_3_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trrp_3_Customer_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Emails", });
    internal_static_trrp_3_Customer_EmailAddress_descriptor =
      internal_static_trrp_3_Customer_descriptor.getNestedTypes().get(0);
    internal_static_trrp_3_Customer_EmailAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trrp_3_Customer_EmailAddress_descriptor,
        new java.lang.String[] { "Email", "Type", });
    internal_static_trrp_3_ListCustomers_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trrp_3_ListCustomers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trrp_3_ListCustomers_descriptor,
        new java.lang.String[] { "Items", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
